Fixed payment and delivery status bug in order page
roopeshsn/freshbey pull request #108
Opened 2022-10-18 17:00 UTC by neeladripal

@roopeshsn 
This PR resolves #101 .

https://user-images.githubusercontent.com/60524775/196495545-563226d7-0a6a-4aee-b03a-a3ccae79b8ff.mov

Payment status is updated as soon as "Mark as Paid" button is clicked.
Delivery status is updated as soon as "Mark as Delivered" is clicked.
Both actions do not require refreshing the window for the update to render.

2022-10-20 01:03 UTC, roopeshsn commented
At 0.17 in the attached video, when you clicked the "Mark as paid" button, the name and email fields disappeared. Here's the screenshot,
![bug_in_order_route](https://user-images.githubusercontent.com/70762571/196832248-a17ffcc5-558b-49b8-882d-094d2b360714.jpg)

2022-10-21 15:50 UTC, neeladripal commented
https://user-images.githubusercontent.com/60524775/197236861-957a3e94-0591-4b69-9d8f-10420aa16638.mov

fixed

2022-10-29 09:40 UTC, roopeshsn requested changes
Kindly reply.

2022-10-29 09:43 UTC, roopeshsn commented
Hey, @neeladripal  Are you not interested to get this PR merged?

2022-10-29 10:10 UTC, neeladripal commented on backend/controllers/orderControllers.js
> +    await updatedOrder.populate(
The order object has the object id of the customer as its attribute. We need to populate it with customer name and email. On payment success, order screen's state is updated with the value returned from updateOrder api.

2022-10-29 10:28 UTC, neeladripal commented
> 

@roopeshsn I think the bug is resolved. Merging is on you.

2022-10-30 10:54 UTC, merged