Simplify image upload for admin in products
roopeshsn/freshbey pull request #74
Opened 2022-10-05 16:44 UTC by s-vamshi

2022-10-05 17:09 UTC, SyedMuzamilM commented
Code looks ok. Can you share a demo video so that we can see how is it working. Try to upload an image and then show the product page for which you uploaded this image.

2022-10-05 17:21 UTC, s-vamshi commented
Here is the working demo -

https://user-images.githubusercontent.com/62489114/194122268-d844b25a-1b9b-4c2e-8945-33f872d5a949.mp4

2022-10-07 14:36 UTC, roopeshsn commented
Thanks for bearing with me @s-vamshi I'll summarize what you've done. If I am wrong correct me. 

- The first step is getting the image from the user and immediately uploading it to the Cloudinary storage. 
- Then the app is waiting to receive the image URL from the Cloudinary. 
- Once the URL is received then along with other data like name, price, etc. will be saved to the DB. 

Am I right?

I have some questions to address. 

- If the user not selecting the image then what will be the message shown to the user? 
- What if Cloudinary service is down? How the app handles it? 

You have used the try-catch block. It will be nice if you simulate an error and add a screenshot if possible.

2022-10-07 15:23 UTC, roopeshsn commented
No simulating Cloudinary error is not required. Is there any way to change the message meaningful?

2022-10-07 15:38 UTC, roopeshsn commented
Also, have you taken care of when the admin wants to edit the product image?

2022-10-07 15:42 UTC, roopeshsn commented
> @roopeshsn No problem. Yes you are right.
> 
> 1. If the user is not selecting the image this message is shown -
>    ![image](https://user-images.githubusercontent.com/62489114/194584195-5bfb5ef0-106e-44bb-bcb6-d95748878c94.png)
> 2. Tbh I don't know how the app will respond when cloudinary service is down, I need to check if there is any way to simulate if service is down.
> 3. Yes I will simulate and add a screenshot

No, I am asking about what if the user selects a video or a text file?

2022-10-07 16:16 UTC, s-vamshi commented
> Also, have you taken care of when the admin wants to edit the product image?

**NO**
Thanks for pointing this out, I will start working on product edit page also.

2022-10-07 16:26 UTC, s-vamshi commented
> > @roopeshsn No problem. Yes you are right.
> > 
> > 1. If the user is not selecting the image this message is shown -
> >    ![image](https://user-images.githubusercontent.com/62489114/194584195-5bfb5ef0-106e-44bb-bcb6-d95748878c94.png)
> > 2. Tbh I don't know how the app will respond when cloudinary service is down, I need to check if there is any way to simulate if service is down.
> > 3. Yes I will simulate and add a screenshot
> 
> No, I am asking about what will be the case if the user selects a video or a text file.

It will not upload to cloud hence image Src state will be an empty string
And this is how it looks without any error msg we need to display an error message right?
![tem11](https://user-images.githubusercontent.com/62489114/194600946-1bd8ab70-1360-4877-a042-54810d7cad04.PNG)

2022-10-07 16:30 UTC, roopeshsn commented
> > > @roopeshsn No problem. Yes you are right.
> > > 
> > > 1. If the user is not selecting the image this message is shown -
> > >    ![image](https://user-images.githubusercontent.com/62489114/194584195-5bfb5ef0-106e-44bb-bcb6-d95748878c94.png)
> > > 2. Tbh I don't know how the app will respond when cloudinary service is down, I need to check if there is any way to simulate if service is down.
> > > 3. Yes I will simulate and add a screenshot
> > 
> > 
> > No, I am asking about what will be the case if the user selects a video or a text file.
> 
> It will not upload to cloud hence image Src state will be an empty string And this is how it looks without any error msg we need to display an error message right? ![tem11](https://user-images.githubusercontent.com/62489114/194600946-1bd8ab70-1360-4877-a042-54810d7cad04.PNG)

Yes, we need to take care of all the edge cases.

2022-10-07 17:01 UTC, roopeshsn commented
As of now, I will merge the PR up to what you've done. Y After that you can work on the edit product route. What's your thought?

2022-10-07 17:01 UTC, roopeshsn requested changes

2022-10-07 17:25 UTC, s-vamshi commented on backend/routes/uploadRoutes.js
> +const { CloudinaryStorage } = require("multer-storage-cloudinary")
Instead of storage to local system using multer we are using a similar package called multer storage cloudinary to store images directly in cloud.
And to upload images we need api keys so we need to use cloudinary package.

2022-10-07 17:26 UTC, s-vamshi commented on backend/routes/uploadRoutes.js
> +cloudinary.config({
I think yes can i make all this changes tomorrow?

2022-10-07 17:41 UTC, roopeshsn commented on backend/routes/uploadRoutes.js
> +cloudinary.config({
No problem. Take your own time. I highly encourage you to contribute in your free time!

2022-10-07 17:52 UTC, s-vamshi commented on backend/routes/uploadRoutes.js
> +cloudinary.config({
Thank you

2022-10-08 05:46 UTC, s-vamshi commented on backend/routes/uploadRoutes.js
> +cloudinary.config({
@roopeshsn I have moved cloud config to db/config.

2022-10-08 05:46 UTC, s-vamshi commented
> No simulating Cloudinary error is not required. Is there any way to change the error message meaningful?
@roopeshsn 
Modified all error messages while submitting form
![tem12](https://user-images.githubusercontent.com/62489114/194690614-e207de97-a9d7-478e-a86f-eba733616b46.PNG)
![temp11](https://user-images.githubusercontent.com/62489114/194690621-3aa468d6-efa4-45e7-978b-5e952f4a8ac8.PNG)

2022-10-08 06:39 UTC, s-vamshi commented
> No, I am asking about what will be the case if the user selects a video or a text file.

**Made changes now when user uploads other files displays this msg -**
![image](https://user-images.githubusercontent.com/62489114/194693629-1fbf0869-d3d5-4837-ac73-d5c7d11817f4.png)

2022-10-08 07:13 UTC, s-vamshi commented
> Also, have you taken care of when the admin wants to edit the product image?

@roopeshsn This is the change i have made in edit product page. Is it ok?
![image](https://user-images.githubusercontent.com/62489114/194695008-c25969b3-da94-4360-96b2-5b854cf8a4a5.png)

2022-10-08 12:13 UTC, roopeshsn commented
> > Also, have you taken care of when the admin wants to edit the product image?
> 
> @roopeshsn This is the change i have made in edit product page. Is it ok? ![image](https://user-images.githubusercontent.com/62489114/194695008-c25969b3-da94-4360-96b2-5b854cf8a4a5.png)

There is no need to render the previous product image.

2022-10-08 13:43 UTC, s-vamshi commented
> There is no need to render the previous product image.

@roopeshsn removed previous product image.
But found a bug which is not related to current issue or commits

2022-10-08 15:37 UTC, roopeshsn commented
> > There is no need to render the previous product image.
> 
> @roopeshsn removed previous product image. But found a bug which is not related to current issue or commits. So the bug is when we are in admin/productlist route, when we click on edit button and update a product then we will get again redirected to admin/productlist. Here starts the problem now when we want to edit any other product we will get an error Uncaught TypeError: Cannot read properties of undefined (reading 'name') at ProductEditScreen.js:47:1

Yes, this bug persists. If possible could you create an issue for the same?

2022-10-08 15:41 UTC, s-vamshi commented
Ok. I will create an issue and can you review my PR ?

2022-10-08 15:52 UTC, roopeshsn commented
How we can handle this? If I am a product is getting updated with a new image and then the old image should get deleted in Cloudinary. Would like to know your thoughts.

2022-10-08 15:52 UTC, roopeshsn commented
> Ok. I will create an issue and can you review my PR ?

So updating a product with a new image is working fine right?

2022-10-08 15:56 UTC, s-vamshi commented
> How we can handle this? If I am a product is getting updated with a new image and then the old image should get deleted in Cloudinary. Would like to know your thoughts.

Ya this is a great idea I will start working on it.

2022-10-08 15:56 UTC, s-vamshi commented
> > Ok. I will create an issue and can you review my PR ?
> 
> So updating a product with a new image is working fine right?

Yes

2022-10-08 15:58 UTC, roopeshsn commented
Wait, I will merge this PR. The code is not formatted properly. We have a prettier command to format recursively. Check the package.json file.

2022-10-08 16:12 UTC, roopeshsn approved these changes

2022-10-08 16:13 UTC, merged

2022-10-08 16:13 UTC, roopeshsn commented
Appreciate your work @s-vamshi

2022-10-10 11:40 UTC, s-vamshi commented
> How we can handle this? If I am a product is getting updated with a new image and then the old image should get deleted in Cloudinary. Would like to know your thoughts.

@roopeshsn should i start working on this feature or should i wait until 404 page feature gets merged?