Added appropriate delivery info
roopeshsn/freshbey pull request #75
Opened 2022-10-05 18:14 UTC by ankitdas09

Issue #51 
<img width="1337" alt="Screenshot 2022-10-05 at 23 32 20" src="https://user-images.githubusercontent.com/97328831/194130335-13d78de9-22b9-4567-98c0-ff6043df49b6.png">
<img width="881" alt="Screenshot 2022-10-05 at 23 32 40" src="https://user-images.githubusercontent.com/97328831/194130371-1226f501-983d-4970-84e8-5ef75f7fa546.png">
<img width="888" alt="Screenshot 2022-10-05 at 23 38 33" src="https://user-images.githubusercontent.com/97328831/194131267-248f8fb2-316e-4f58-aee1-e6f6540a6ab4.png">
<img width="425" alt="Screenshot 2022-10-05 at 23 33 18" src="https://user-images.githubusercontent.com/97328831/194130409-cf7d16b7-a2e7-4038-8a44-e8b16542c728.png">
<img width="431" alt="Screenshot 2022-10-05 at 23 33 33" src="https://user-images.githubusercontent.com/97328831/194130424-5c69c5bd-feb4-446b-bf21-d06831555347.png">

2022-10-08 12:21 UTC, roopeshsn commented
Hi, @ankitdas09 Thanks for bearing with me! How it will be If the color of this icon changes to warning yellow?
![194130424-5c69c5bd-feb4-446b-bf21-d06831555347](https://user-images.githubusercontent.com/70762571/194707289-343f2e38-ec33-41e0-a71f-16e813aca0cd.png)

2022-10-08 12:24 UTC, roopeshsn requested changes

2022-10-08 12:24 UTC, roopeshsn commented on frontend/src/screens/CartScreen.js
> +import { TiTick } from 'react-icons/ti'
Why you haven't committed the package.json and package-lock.json as you included icons from the react-icons package?

2022-10-09 07:54 UTC, ankitdas09 commented on frontend/src/screens/CartScreen.js
> +import { TiTick } from 'react-icons/ti'
https://github.com/roopeshsn/freshbey/blob/75f538bb958649b610f889359a7579b5bca24e83/frontend/package.json#L15
Since I have not installed any new packages, react-icons was already installed as a dependency.

2022-10-09 07:55 UTC, ankitdas09 commented
@roopeshsn Sure, I will change the color to yellow.

2022-10-09 08:47 UTC, roopeshsn commented on frontend/src/screens/CartScreen.js
> +import { TiTick } from 'react-icons/ti'
Yeah, I am wrong.

2022-10-09 11:37 UTC, roopeshsn commented
At last format the code with the prettier command. Check the package.json file.

2022-10-09 11:58 UTC, ankitdas09 commented
> At last format the code with the prettier command. Check the package.json file.

@roopeshsn Sure.

2022-10-10 13:45 UTC, merged