Added inventory management
roopeshsn/freshbey pull request #80
Opened 2022-10-08 07:50 UTC by BiswajitSahoo-tech

Hi @roopeshsn,
I have added inventory management, below is a brief of my solution:

1. First created a `updateStockCount` function on `backend/controller/productController/`
    few notes on the `updateStockCount` function and how it handles the edge cases
    - `var product = await Product.findById(id)`  - find the product by id passed as argument
    -  ```
        if(product.countInStock < qty){
              throw new Error(" A MESSAGE")
        }  
       ```  
       The above code throws an Error if the Quantity demanded is more than in stock amount of any product present on 
       `OrderItem`
    - Finally, if everything goes well, then the below code will be executed and stock will be updated for each product 
      corresponding to the given order.
      ```
      product.countInStock -= qty
      const updatedProduct = await product.save()
      ```
2. Add the following code in `updateOrderToPaid` function under `backend/controller/orderController/`
 ```
    const updatePromises = order.orderItems.map(async (item)=> {
      await productController.updateStockCount( req, res, item.product,parseInt( item.qty))
    })
    //below function to resolve the array of promises
    try{
      await Promise.all( updatePromises)
    }catch( error){
      return res.status(404).json({
        status:'fail',
        message: error.message
      })
    }
    
```
`catch(err)` will catch the error thrown by `updateStockCount` and immediately send a response to the client having appropriate
the message of what actually happens also ends the **request-response** cycle such that in the case of a catch there will be no update on these fields.
`isPaid` and `paidAt` - these fields are updated only when all the promises at ` updatePromises` will be resolved successfully.
 ```
order.isPaid = true
 order.paidAt = Date.now()
```
The above code will execute only when all the promises at ` updatePromises` will be resolved successfully.

Thank You ❤️

2022-10-08 12:46 UTC, roopeshsn commented
Hi, @BiswajitSahoo-tech Could you also check with the frontend and add an appropriate video or a screenshot?

2022-10-08 13:09 UTC, BiswajitSahoo-tech commented
Ok @roopeshsn, Got it
Thanks

2022-10-08 14:29 UTC, BiswajitSahoo-tech commented
Hi @roopeshsn,
Below are the screenshots following the flow

1.  User goes to a product page and adds it to the cart (Note: status is In Stock)
![fb-ss-1](https://user-images.githubusercontent.com/73599660/194711093-843d645a-9cc7-4fcc-b14b-7e4dadbd23a5.png)

2.  User goes to cart and clicks **Proceed to checkout**
![fb-ss-2](https://user-images.githubusercontent.com/73599660/194711291-779fdc0a-d8e7-4562-ae61-9ecc56c9ae14.png)

3. After following all the intermediate steps, the User places the order
![fb-ss-3](https://user-images.githubusercontent.com/73599660/194711377-77cccf49-62ba-468c-923c-5689d33f3bca.png)

5. Now we make **PUT** request to `api/orders/63417f09c2fadfe36a1f7699/pay`, since we have to pay for the order in order to have updated the stock amount
![fb-ss-4](https://user-images.githubusercontent.com/73599660/194711509-c9830ecf-f7b5-4f4c-928f-354df67080e0.png)

6. After making the payment, see the status of the paid order page
![fb-ss-5](https://user-images.githubusercontent.com/73599660/194712172-f2ea8904-e6b5-4425-b4c9-70baad86fbc3.png)

7. Now also check the product page: ( Note: Status is now Out of stock)
![fb-ss-6](https://user-images.githubusercontent.com/73599660/194712230-bca41ef7-f040-421f-b00c-afdb331abc7d.png)

Actually initially there is 5 kg carrot in stock and user ordered 5 kg carrots, therefore after payment we have carrot out of stock

2022-10-08 14:30 UTC, BiswajitSahoo-tech commented
@roopeshsn, Please have a look.

2022-10-09 00:50 UTC, roopeshsn commented
Hi @BiswajitSahoo-tech Could you remove that .env.sample file and all its imports? We have .env in the root. Also, the code is not formatted. There is a prettier command to format the recursively check the package.json file.

2022-10-09 01:15 UTC, BiswajitSahoo-tech commented
Hi @roopeshsn, 
I have formatted the code and removed the `.env.sample` file.
Please review it.

2022-10-09 01:16 UTC, roopeshsn requested changes

2022-10-09 01:20 UTC, BiswajitSahoo-tech commented on backend/controllers/productController.js
> +  return updateProduct
`return updateProduct` this line?
This is added such that it will be in the resolved result of all promises that we awaiting in orderController.
But there is no requirement for this result, we can omit this.

2022-10-09 01:25 UTC, BiswajitSahoo-tech commented on package.json
> +
@roopeshsn  I removed it, check it now please

2022-10-09 01:39 UTC, roopeshsn commented
Good work @BiswajitSahoo-tech Let me know if you're interested to become a collaborator for this project.

2022-10-09 01:39 UTC, roopeshsn approved these changes

2022-10-09 01:40 UTC, merged

2022-10-09 01:41 UTC, BiswajitSahoo-tech commented
Thanks, @roopeshsn, for giving me this opportunity.
Just a doubt, what are the works of a project collaborator?

2022-10-09 01:48 UTC, roopeshsn commented
The work of a maintainer or owner of a project. Collaborator will raise issues for a feature or a bug, review and merge PRs. In short, Collaborator will work for the improvement of the project.

2022-10-09 01:51 UTC, BiswajitSahoo-tech commented
Sorry, @roopeshsn, we have a term exam scheduled next week so, I don't think I can contribute much as a collaborator. Thank you very much for the offer.