Number of Items Issue Solved
roopeshsn/freshbey pull request #93
Opened 2022-10-12 10:46 UTC by ranjankuldeep

#92 

# The Cart is working as expected now.
## Here is the ScreenShot showing correct number of items.
I have tested many possibilities of adding to the cart and editing in the cart, Everythings work fine.

 
<img width="850" alt="Screenshot 2022-10-12 at 4 10 54 PM" src="https://user-images.githubusercontent.com/95350799/195322123-0b0c16d6-c532-4987-ac12-5e9421212e08.png">

@roopeshsn

2022-10-12 14:29 UTC, roopeshsn requested changes

2022-10-12 14:29 UTC, roopeshsn commented on frontend/src/screens/CartScreen.js
> +    (acc, item) => acc + +item.qty * +item.price,
What did this plus sign (+) do?

2022-10-12 14:36 UTC, ranjankuldeep commented on frontend/src/screens/CartScreen.js
> +    (acc, item) => acc + +item.qty * +item.price,
The unary plus operator (+) precedes its operand and evaluates to its operand but attempts to convert it into a number, if it isn't already.

It basically makes string to number.
So these are now no longer added as string but as a number.
@roopeshsn

2022-10-12 14:40 UTC, roopeshsn commented on frontend/src/screens/CartScreen.js
> +    (acc, item) => acc + +item.qty * +item.price,
Why have you not used a function? It will improve readability instead of using the unary plus operator.

2022-10-12 14:41 UTC, ranjankuldeep commented on frontend/src/screens/CartScreen.js
> +    (acc, item) => acc + +item.qty * +item.price,
We can also go with the parseInt(),
But i choosen '+' operator here.

2022-10-12 14:44 UTC, ranjankuldeep commented on frontend/src/screens/CartScreen.js
> +    (acc, item) => acc + +item.qty * +item.price,
Ohhk so I will make the changes.
Will be using function now .

2022-10-12 14:51 UTC, roopeshsn commented
Also, format the code using the prettier command. Check the package.json file.

2022-10-13 01:01 UTC, ranjankuldeep commented
Please Review,
I have made the necessary changes. @roopeshsn

2022-10-13 01:35 UTC, roopeshsn requested changes

2022-10-13 01:35 UTC, roopeshsn commented on frontend/src/screens/CartScreen.js
> +                        value={+item.qty}
Why have you not changed here?

2022-10-13 01:35 UTC, roopeshsn commented on frontend/src/screens/CartScreen.js
> +                Subtotal ({cartItems.reduce((acc, item) => acc + +item.qty, 0)})
Here too

2022-10-13 01:47 UTC, ranjankuldeep commented on frontend/src/screens/CartScreen.js
> +                Subtotal ({cartItems.reduce((acc, item) => acc + +item.qty, 0)})
Ahh,  I missed that.

2022-10-13 01:47 UTC, roopeshsn commented
Whether there the changes didn't affect the working of the application right? Have you formatted the code using prettier?

2022-10-13 01:48 UTC, ranjankuldeep commented
I made the changes in the cart screen. 
@roopeshsn

2022-10-13 01:49 UTC, roopeshsn commented
> Whether there the changes didn't affect the working of the application right? Have you formatted the code using prettier?

Reply appropriately!

2022-10-13 01:50 UTC, ranjankuldeep commented
yes i formatted ,
i run the command 
```
npm run prettier 
```
I didn't get the first question.

2022-10-13 01:52 UTC, ranjankuldeep commented
The application is working fine now.
I added changes only where quantity was involved so that it won't break at any point

2022-10-13 01:56 UTC, roopeshsn commented
Man answer in a single shot. What about prettier?

2022-10-13 01:57 UTC, merged